Repository Isasanelli/Adventure, pull requests merged in 2022-06, with the labels that each got.

#12 modifica parte file
  GameTheHuntress/file/stanza1.1.txt
  GameTheHuntress/resources/db/playgame.mv.db
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/Engine.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/eventi/DbClass.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/eventi/Eventi.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/games/TheHuntressGame.java
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/Engine.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/eventi/Eventi.class
Labels: bug

#14 Effettuate modifiche e aggiunte previste
  GameTheHuntress/resources/db/playgame.mv.db
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/Engine.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/GameDescription.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/games/TheHuntressGame.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/AdvObject.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/AdvObjectContainer.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/Room.java
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/Engine.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/GameDescription.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/games/TheHuntressGame.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/AdvObject.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/AdvObjectContainer.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/Room.class
Labels: bug, implementazione

#17 Inseriti gli oggetti contenitori e sistemato la classe oggetti
  GameTheHuntress/resources/db/playgame.mv.db
  GameTheHuntress/src/main/java/com/gioco/thehuntress/eventi/DbClass.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/games/TheHuntressGame.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/AdvObject.java
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/Engine.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/games/TheHuntressGame.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/AdvObject.class
Labels: implementazione

#20 Eliminazione metodo close nella classe db e modifica di nome in name
  GameTheHuntress/resources/db/playgame.mv.db
  GameTheHuntress/src/main/java/com/gioco/thehuntress/eventi/DbClass.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/AdvObject.java
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/AdvObject.class
Labels: bug

#22 Modifiche varie su db, classe Engine, classe Parsel e classe AdvObject
  GameTheHuntress/resources/db/playgame.mv.db
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/Engine.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/eventi/DbClass.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/games/TheHuntressGame.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/parser/Parser.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/AdvObject.java
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/Engine.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/games/TheHuntressGame.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/AdvObject.class
Labels: bug

#24 Fatte ulteriori modifiche e aggiunte
  GameTheHuntress/resources/db/playgame.mv.db
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/Engine.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/Utils.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/eventi/DbClass.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/games/TheHuntressGame.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/parser/Parser.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/AdvObject.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/Room.java
  GameTheHuntress/target/classes/com/gioco/thehuntress/games/TheHuntressGame.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/AdvObject.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/Room.class
Labels: bug, implementazione

#26 settaggio delle variabili nelle stanze e implementazione del movimento tra le stanze
  GameTheHuntress/file/roomGarden.txt
  GameTheHuntress/file/roomTrainingCamp.txt
  GameTheHuntress/file/stanza1.1.txt
  GameTheHuntress/resources/db/playgame.mv.db
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/Engine.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/eventi/DbClass.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/games/TheHuntressGame.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/Room.java
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/Engine.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/games/TheHuntressGame.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/Room.class
Labels: implementazione

#29 SISTEMAZIONE STANZA 3
  GameTheHuntress/file/roomValleyOfDeath.txt
  GameTheHuntress/resources/db/playgame.mv.db
  GameTheHuntress/src/main/java/com/gioco/thehuntress/eventi/DbClass.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/games/TheHuntressGame.java
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/Engine.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/games/TheHuntressGame.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/Room.class
Labels: implementazione

#31 settaggio delle stanze con rispettive coordinate.
  GameTheHuntress/.idea/misc.xml
  GameTheHuntress/file/regole.txt
  GameTheHuntress/file/roomTrainingCamp.txt
  GameTheHuntress/file/roomValleyOfDeath.txt
  GameTheHuntress/resources/db/playgame.mv.db
  GameTheHuntress/src/main/java/com/gioco/thehuntress/eventi/DbClass.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/games/TheHuntressGame.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/Room.java
  GameTheHuntress/target/classes/com/gioco/thehuntress/games/TheHuntressGame.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/Room.class
Labels: implementazione

#37 Sistemato main
  GameTheHuntress/.idea/misc.xml
  GameTheHuntress/resources/db/playgame.mv.db
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/Engine.java
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/Engine.class
Labels: bug

#39 pull 15/06
  GameTheHuntress/.idea/inspectionProfiles/Project_Default.xml
  GameTheHuntress/file/stopwords
  GameTheHuntress/pom.xml
  GameTheHuntress/resources/db/playgame.mv.db
  GameTheHuntress/resources/db/playgame.trace.db
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/Engine.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/GameDescription.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/Grafica.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/eventi/DbClass.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/eventi/MapGraphic.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/games/TheHuntressGame.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/parser/Parser.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/parser/ParserOutput.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/AdvObject.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/Command.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/CommandType.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/Room.java
  GameTheHuntress/target/classes/.netbeans_automatic_build
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/Engine.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/GameDescription.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/Grafica.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/eventi/Eventi.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/games/TheHuntressGame.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/AdvObject.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/Command.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/CommandType.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/Room.class
  GameTheHuntress/target/test-classes/.netbeans_automatic_build
Labels: implementazione

#41 17/06
  GameTheHuntress/resources/db/playgame.mv.db
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/Engine.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/Grafica.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/Utils.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/eventi/DbClass.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/games/TheHuntressGame.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/parser/Parser.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/AdvObject.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/CommandType.java
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/Engine.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/Grafica.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/games/TheHuntressGame.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/AdvObject.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/CommandType.class
Labels: bug, implementazione

#47 Risolvere il problema dei comandi e dei file
  GameTheHuntress/file/roomGarden.txt
  GameTheHuntress/file/roomTend.txt
  GameTheHuntress/file/roomTrainingCamp.txt
  GameTheHuntress/file/roomValleyOfDeath.txt
  GameTheHuntress/resources/db/playgame.mv.db
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/Engine.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/Grafica.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/games/TheHuntressGame.java
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/Engine.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/Grafica.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/games/TheHuntressGame.class
Labels: bug

#49 SISTEMARE COMANDI
  GameTheHuntress/file/comandi.txt
  GameTheHuntress/file/roomGarden.txt
  GameTheHuntress/file/roomTend.txt
  GameTheHuntress/file/roomTrainingCamp.txt
  GameTheHuntress/file/roomValleyOfDeath.txt
  GameTheHuntress/resources/db/playgame.mv.db
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/Engine.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/GameDescription.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/eventi/DbClass.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/eventi/MapGraphic.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/eventi/ReadFileDialog.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/games/TheHuntressGame.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/Inventory.java
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/Engine.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/GameDescription.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/games/TheHuntressGame.class
Labels: bug, implementazione

#51 19/06
  GameTheHuntress/.idea/misc.xml
  GameTheHuntress/file/roomGarden.txt
  GameTheHuntress/file/roomTend.txt
  GameTheHuntress/file/roomTrainingCamp.txt
  GameTheHuntress/file/roomValleyOfDeath.txt
  GameTheHuntress/resources/db/playgame.mv.db
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/Engine.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/eventi/DbClass.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/games/TheHuntressGame.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/AdvObject.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/Room.java
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/Engine.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/games/TheHuntressGame.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/AdvObject.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/Room.class
Labels: implementazione

#53 Sistemazione db e parla
  GameTheHuntress/.idea/misc.xml
  GameTheHuntress/file/roomGarden.txt
  GameTheHuntress/file/roomTrainingCamp.txt
  GameTheHuntress/resources/db/playgame.mv.db
  GameTheHuntress/src/main/java/com/gioco/thehuntress/eventi/DbClass.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/games/TheHuntressGame.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/AdvObject.java
  GameTheHuntress/target/classes/com/gioco/thehuntress/games/TheHuntressGame.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/AdvObject.class
Labels: bug, implementazione

#56 Pull request santissima
  GameTheHuntress/Immagini/Mappa.jpeg
  GameTheHuntress/Immagini/Mappa.png
  GameTheHuntress/file/roomCollolungo.txt
  GameTheHuntress/file/roomTrainingCamp.txt
  GameTheHuntress/file/stopwords
  GameTheHuntress/resources/db/playgame.mv.db
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/Engine.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/Utils.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/eventi/DbClass.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/eventi/MapGraphic.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/games/TheHuntressGame.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/minigame/TicTacGame.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/parser/Parser.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/parser/ParserOutput.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/AdvObject.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/CommandType.java
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/Engine.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/games/TheHuntressGame.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/minigame/TicTacGame.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/AdvObject.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/CommandType.class
Labels: implementazione

#60 modifica dei file
  GameTheHuntress/GameTheHuntress.iml
  GameTheHuntress/file/comandi.txt
  GameTheHuntress/file/roomCalderoneLoser.txt
  GameTheHuntress/file/roomCalderoneWin.txt
  GameTheHuntress/file/roomCollolungo.txt
  GameTheHuntress/file/roomGarden.txt
  GameTheHuntress/file/roomTend.txt
  GameTheHuntress/file/roomValleyOfDeath.txt
  GameTheHuntress/resources/db/playgame.mv.db
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/Engine.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/GameDescription.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/battle/MiniGameBattle.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/battle/Opponent.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/battle/User.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/database/DbClass.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/games/TheHuntressGame.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/graphic/Grafica.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/minigame/BoxTextMingame.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/parser/Parser.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/parser/ParserOutput.java
  GameTheHuntress/target/GameTheHuntress-1.0-SNAPSHOT.jar
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/Engine.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/GameDescription.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/eventi/Eventi.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/games/TheHuntressGame.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/minigame/TicTacGame.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/AdvObject.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/AdvObjectContainer.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/Command.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/CommandType.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/Inventory.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/Room.class
  GameTheHuntress/target/maven-archiver/pom.properties
  GameTheHuntress/target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  GameTheHuntress/target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  GameTheHuntress/target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
Labels: implementazione

#63 27/06
  GameTheHuntress/file/comandi.txt
  GameTheHuntress/file/roomCalderoneLoser.txt
  GameTheHuntress/file/roomCalderoneWin.txt
  GameTheHuntress/file/roomGarden.txt
  GameTheHuntress/file/roomTend.txt
  GameTheHuntress/file/roomValleyOfDeath.txt
  GameTheHuntress/resources/db/playgame.mv.db
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/Engine.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/GameDescription.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/adventure/Utils.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/battle/MiniGameBattle.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/battle/Move.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/battle/Opponent.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/battle/User.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/database/DbClass.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/eventi/Eventi.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/games/TheHuntressGame.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/graphic/Grafica.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/graphic/MapGraphic.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/minigame/BoxTextMingame.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/minigame/RestartMiniGame.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/minigame/TicTacGame.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/parser/Parser.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/parser/ParserOutput.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/AdvObject.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/AdvObjectContainer.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/Command.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/CommandType.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/Inventory.java
  GameTheHuntress/src/main/java/com/gioco/thehuntress/type/Room.java
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/Engine.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/adventure/GameDescription.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/eventi/Eventi.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/games/TheHuntressGame.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/minigame/TicTacGame.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/AdvObject.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/AdvObjectContainer.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/Command.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/CommandType.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/Inventory.class
  GameTheHuntress/target/classes/com/gioco/thehuntress/type/Room.class
Labels: bug, implementazione
